### ISSUE TITLE
Need information for 3 strings

### ISSUE THREAD

**Issue by gunchleoc** [django/django-contrib-comments#104]
Issues reported on Transifex:

    forms.py:99

    Comment

> Is this a noun or a verb?

    models.py:179

    flag

> noun or verb ?
> literal translation seldomly used in Dutch.
> Need more context to translate correctly.

    templates/comments/preview.html:16

    or make changes

> not translatable, need more context

If you post an answer here, I'll be happy to pass on the information.

**Comment by claudep** [comment]
Could you please review the pull request?

**Comment by gunchleoc** [comment]
Looking good, thanks :)

**Comment by claudep** [comment]
Thanks for the review. You are not supposed to close it yourself before I merge it :-)

**Comment by gunchleoc** [comment]
Oops, thanks for reopening :)
