### ISSUE TITLE
get_comment_create_data() got an unexpected keyword argument 'site_id'

### ISSUE THREAD

**Issue by nordbit** [django/django-contrib-comments#115]
in:
views/comments.py
forms.py

Django==1.10.5 & django-contrib-comments==1.7.3/current

No error with oldest version django-contrib-comments == 1.7.2

**Comment by claudep** [comment]
I guess you have your own `get_comment_create_data` method? I'd then suggest to add `**kwargs` in the signature of your version.
This was changed in https://github.com/django/django-contrib-comments/commit/1ab69cb122418c973e27210558d11bb3fba921f6
