### ISSUE TITLE
Refer to the user_email on which comment I want to reply

### ISSUE THREAD

**Issue by Copser** [django/django-contrib-comments#121]
How can I refer to a user on which comment I want to reply, from the [docs](http://django-contrib-comments.readthedocs.io/en/latest/models.html#django_comments.models.Comment.user_email), I can see that the

> user_email The email of the user who posted the comment.

and that is fine I'm using it in my code so I could send and email to the user who will comment, but I want to send him a notification mail when someone else reply to that user comment, so in this case they will be notified, so is there a way to refer to the `email` of the user I want to reply?

Here is a [gist](https://gist.github.com/Copser/f03eb0ac1514eabcc3f9b16d8a074a73) of my comment email system notification so you will have more info on the stuff I wan't to do.

Thanks

**Comment by Copser** [comment]
Hello I'm closing this because I found out that in the other package [django-threadedcomments](https://github.com/HonzaKral/django-threadedcomments/blob/master/threadedcomments/models.pyl) there is a `parent` model field which can be referred to the user who left a comment, so now my reply email notification works properly.

Maybe update the docs to give people a hint that this project is related to [django-threadedcomments](https://github.com/HonzaKral/django-threadedcomments) and [django-fluent-comments](https://github.com/django-fluent/django-fluent-comments#django-fluent-comments).

Cheers

**Comment by chris542** [comment]
@Copser Hey thanks for this! You saved my day!
