### ISSUE TITLE
Release a new version to resolve Django 2.1 compatibility

### ISSUE THREAD

**Issue by dcollinsn** [django/django-contrib-comments#137]
Currently the most current version of django-contrib-comments on pypi is 1.8.0, which is not compatible with Django 2.1, due to views/utils.py's use of django.utils.http's is_safe_url, which had an API change. This issue is resolved by https://github.com/django/django-contrib-comments/commit/e94b557f8fb0fd8e7272e0168a688083086d21ce#diff-79c5990d4a074dd413b23f20daa4312e .

Please consider cutting a release of the current `master` branch whenever possible to add compatibility with Django 2.1. Thanks!

**Comment by claudep** [comment]
1.9.0 has just been released.
