### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by dengwen168** [django/django-contrib-comments#152]
When i click the "submit" button, I got the following information:

Request Method: | POST
-- | --
http://127.0.0.1:8000/comments/post/
2.0
IndexError
list index out of range
H:\py_project\weather\weathervenv\lib\site-packages\django\db\models\query.py in __getitem__, line 307
H:\py_project\weather\weathervenv\Scripts\python.exe
3.6.5

**Comment by jhabarsingh** [comment]
can i work on this issue ?

**Comment by claudep** [comment]
Of course, but do you think you have enough information to find the root cause?

**Comment by jhabarsingh** [comment]
yeah i feel the information is not sufficient, to work on this issue. sorry for that .

**Comment by claudep** [comment]
No problem, closing for lack of reproducible information.
