### ISSUE TITLE
Documentation bug: get_comment_create_data() requires **kwargs

### ISSUE THREAD

**Issue by a1tsal** [django/django-contrib-comments#156]
In `https://django-contrib-comments.readthedocs.io/en/latest/custom.html`, `def get_comment_create_data(self)` is incorrect. It needs `**kwargs`, as found in #115.

**Comment by claudep** [comment]
This seems to be fixed in the master branch. I don't know how to force readthedocs to refresh its pages.

**Comment by claudep** [comment]
The docs were successfully rebuilt today.
