### ISSUE TITLE
Missing template files in PyPI package

### ISSUE THREAD

**Issue by michaeljones** [django/django-contrib-comments#16]
Hi,

From what I can tell, the PyPI package is missing the `templates` folder which means that the templates aren't found when using tags like `{% render_comment_list for [object] %}`. 

Maybe I am confused and need another approach but the documentation doesn't seem to mention anything other than:

> This will render comments using a template named comments/list.html, a default version of which is included with Django.

Which seems to be true for 1.6 which is confusing as I thought this project exists because `contrib.comments` is no longer include in Django. Even so the django-contrib-comments docs don't suggest adding `django.contrib.comments` to `INSTALLED_APPS` to get access to the templates.

I feel like I must be very confused :) Any help would be much appreciated.

Michael

**Comment by vdboor** [comment]
> It appears the project needs an active maintainer other than the django core developers..

Maybe so, but could you at least publish a fixed version that does include template files?
The current setup is broken, making it really hard for people to use it. Hence giving it even less attention.

**Comment by claudep** [comment]
A 1.5.1 release has been published today. New patch which adds Django 1.7/1.8 support have been committed in master. Hopefully a 1.6 release will contain the latest changes.
