### ISSUE TITLE
Broken link in documentation.

### ISSUE THREAD

**Issue by reeshabhranjan** [django/django-contrib-comments#163]
[This link](https://docs.djangoproject.com/en/3.1/_objects/ref/contrib/sites/#enabling-the-sites-framework) on [this page](https://django-contrib-comments.readthedocs.io/en/latest/quickstart.html) is broken. The updated link is [this now.](https://docs.djangoproject.com/en/3.1/ref/contrib/sites/#enabling-the-sites-framework).

**Comment by felixxm** [comment]
@reeshabhranjan Thanks for the report. Would you like to prepare a patch?

**Comment by reeshabhranjan** [comment]
I would like to but I am not sure where to update. I found `...<enabling-the-sites-framework>...` in [this file](https://github.com/django/django-contrib-comments/blob/master/docs/quickstart.txt), but I do not know where it is referring to. Could you help me with that?

**Comment by claudep** [comment]
I guess the issue might be with the `intersphinx_mapping` setting in `docs/conf.py`. According to https://ambition-docs-guide.readthedocs.io/en/latest/ref/intersphinx.html,should the second tuple value be None?
