### ISSUE TITLE
Wheel for v2.0.0 missing on PyPI

### ISSUE THREAD

**Issue by atodorov** [django/django-contrib-comments#165]
Previous version did provide a wheel package. Would be nice if you can upload one for 2.0.0 too. Thanks.

**Comment by claudep** [comment]
Indeed, I didnt push a wheel. What's the added value of a wheel in this case?

**Comment by atodorov** [comment]
> Indeed, I didnt push a wheel. What's the added value of a wheel in this case?

From https://packaging.python.org/overview/#python-binary-distributions:

> In fact, Python’s package installer, pip, always prefers wheels because installation is always faster, so even pure-Python packages work better with wheels.
> ...
> Default to publishing both sdist and wheel archives together, unless you’re creating artifacts for a very specific use case where you know the recipient only needs one or the other.

On a more practical side the application that I work on prefers wheels as well and actually tests for that which failed with the latest version. IMO it is just a good practice to push both unless there's some real issue preventing the binary package builds. For my own packages I've defaulted to pushing both but can't give a more in-depth technical explanation in favor of wheel for a pure-Python package other than having it is just easier.

**Comment by claudep** [comment]
OK, should be available now.
