### ISSUE TITLE
Deprecations RemovedInDjango18Warning 

### ISSUE THREAD

**Issue by qcaron** [django/django-contrib-comments#22]
Hi!

I am using django-contrib-comments with https://github.com/Fantomas42/django-blog-zinnia.

When I try posting the comment, it fails but this may be related to django-zinnia.
Here is the django runserver log I get:

> python2.7/site-packages/django_comments/managers.py:19: RemovedInDjango18Warning: `BaseManager.get_query_set` is deprecated, use `get_queryset` instead.
  qs = self.get_query_set().filter(content_type=ct)

> python2.7/site-packages/django_comments/views/comments.py:89: RemovedInDjango18Warning: Options.module_name has been deprecated in favor of model_name
  "comments/%s_%s_preview.html" % (model._meta.app_label, model._meta.module_name),

> python2.7/site-packages/django_comments/views/comments.py:92: RemovedInDjango18Warning: Options.module_name has been deprecated in favor of model_name
  "comments/%s/%s/preview.html" % (model._meta.app_label, model._meta.module_name),

> "POST /comments/post/ HTTP/1.1" 200 21711 // Preview

> "POST /comments/post/ HTTP/1.1" 500 195984 // Post

I will check if there is something on Zinnia's side.

I am using Python 2.7.6 and Django 1.7.3.

Cheers,
Quentin

**Comment by charettes** [comment]
From the stack trace this doesn't look like an issue with Zinnia.

We should be using `get_queryset` [here](https://github.com/django/django-contrib-comments/blob/8a99ed810e9e94cb9dff1c362b2c4ebe2e37dead/django_comments/managers.py#L19).

**Comment by claudep** [comment]
Thanks for the report, fixed in master
