### ISSUE TITLE
RemovedInDjango18Warning re module_name 

### ISSUE THREAD

**Issue by philgyford** [django/django-contrib-comments#24]
I just moved over to `django-contrib-comments` from `django.contrib.comments`.

When I post a comment I get this:

    /Users/phil/.virtualenvs/django-pepysdiary/lib/python2.7/site-packages/django_comments/views/comments.py:89: RemovedInDjango18Warning: Options.module_name has been deprecated in favor of model_name
      "comments/%s_%s_preview.html" % (model._meta.app_label, model._meta.module_name),

The comment is posted successfully. (Sorry if this is the kind of thing you're well aware of, but I couldn't see it referenced elsewhere.)

**Comment by philgyford** [comment]
Hmm, posting further comments don't seem to generate the same warning. That warning was from the first comment I posted after switching apps.

**Comment by claudep** [comment]
Thanks for the report, fixed in master.
