### ISSUE TITLE
get_comment_list is list, not queryset

### ISSUE THREAD

**Issue by stefanw** [django/django-contrib-comments#26]
When using `get_comment_list` [this line](https://github.com/django/django-contrib-comments/blob/master/django_comments/templatetags/comments.py#L113) converts the queryset of comments into a Python list. This caused a bug in my threaded-comments code, here's why:

I'm using `django-mptt` to render threaded comments and their code expects depth-first ordered nodes for their `recursetree` templatetag. For the nodes to be ordered depth-first, `django-mptt` [checks if the given list of nodes is a queryset](https://github.com/django-mptt/django-mptt/blob/master/mptt/templatetags/mptt_tags.py#L255) and if so, applies the necessary ordering. Since the list is not a queryset and the list is obviously not guaranteed to be in depth-first order, the algorithm fails.

I don't know what consequences it would have to just return a queryset from `get_comment_list` (they mostly behave the same and it would keep evaluation just a bit more lazy). Furthermore, even though the name says "list", I kinda expected a queryset, simply because that would be more Django-style.

As a workaround I set up my own template tag `get_comment_queryset` which returns the `queryset` directly. If changing `get_comment_list` is a no-go, maybe adding a `get_comment_queryset` templatetag might be an option. But I guess this issue shall just serve future threaded comment bug hunters as a reference.

**Comment by claudep** [comment]
At the first sight, I don't see a problem with returning a queryset. Would you mind proposing a patch?
