### ISSUE TITLE
Source release for version 1.5.1

### ISSUE THREAD

**Issue by Fantomas42** [django/django-contrib-comments#37]
Hello,

I see on Pypi that the new release of django-contrib-comments (1.5.1) has only be done on the Wheel format. 

It's cool for a faster installation, but in my case, my package installer (zc.buildout) does not support Wheel packages.

For a better compatibility, could you make a standard source release ?

Regards

**Comment by claudep** [comment]
Sure, done.

**Comment by Fantomas42** [comment]
Thanks, perfect !
