### ISSUE TITLE
"NoReverseMatch at" error

### ISSUE THREAD

**Issue by creu34** [django/django-contrib-comments#44]
Hi,
When adding the tag {% render_comment_form for prestation %} in my template I catch this error :
Reverse for 'django_comments.views.comments.post_comment' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

Everything is installed (see it with pip freeze and I can import the models in a shell).
My IDE does not find the reference when I add the line " url(r'^comments/', include('django_comments.urls')), " in my urls.py. I don't know if it's linked.

So, do you have any idea ? Thank you.

**Comment by claudep** [comment]
Could you please join a full traceback of the error? We'd also need to know your version of Django.

**Comment by claudep** [comment]
Closing for lack of feedback.
