### ISSUE TITLE
Multiple Db hits with authenticated users

### ISSUE THREAD

**Issue by kakai248** [django/django-contrib-comments#48]
I've noticed that for each comment of an authenticated user, it will hit the db once to get the user.

We need a select_related('user') to stop this behavior.

I'm not very experienced with Django however, it seems that putting it in the ```get_queryset``` method of the ```BaseCommentNode``` class will fix the issue.

**Comment by claudep** [comment]
That might be a nice improvement.

**Comment by ivanvenosdel** [comment]
Implementing this is really the only way to solve this as the old solution won't work in Django 1.9.

The old way involved creating a [custom comments app](http://django-contrib-comments.readthedocs.org/en/latest/custom.html) and then adding a related manager to your custom model that would do as you describe. Here is a [broken (in 1.9) example](https://github.com/WimpyAnalytics/django-andablog/commit/40e657ccccb77b02f003515b75f2ce6547da7b05#diff-c702e4a95d6bbd700afe77fa51f83d06).

Unfortunately this is no longer possible as 1.9 prevents importing models from another app (even indirectly) before all app models have been loaded. In practice this means that Django no longer supports inheriting from another app's concrete model.

**Comment by claudep** [comment]
It would be nice if some of you could test the patch.
