### ISSUE TITLE
Initial manage.py migrate execution

### ISSUE THREAD

**Issue by asieira** [django/django-contrib-comments#55]
I would like to suggest the documentation on moving from django.contrib.comments to this package include an additional step. I already had data present, so I needed to run `python manage.py migrate django_comments --fake-initial` or the migration would not happen correctly.

**Comment by claudep** [comment]
Would you mind submitting a pull request?

**Comment by asieira** [comment]
There you go.

**Comment by claudep** [comment]
Fixed by #56.
