### ISSUE TITLE
Could we use PostgreSQL with? "operator does not exist: integer = text" Bug

### ISSUE THREAD

**Issue by gustavklopp** [django/django-contrib-comments#61]
There's a "bug" in postgreSQL (in fact, it's more a feature: strong typed, contrary to MySQL which is "weakly typed", since PostgreSQL 8.3):

Now if you've got:
models.py
```
class ArticlesTable(models.Model):
    id = models.IntegerField(primary_key=True) 
    ...
```

and if you want to display the Articles, whose there's comment, for example, you do:
views.py
`latest_comments = ArticlesTable.objects.filter(comments_set__isnull=False)`

But PostgreSQL doesn't like that!
error:
```
ProgrammingError at /

operator does not exist: integer = text
LINE 1: ...ango_comments" ON ( "articles_articlesTable"."id" = "django_...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

How can we avoid this error when using simple filtering?
Hint here:  http://stackoverflow.com/questions/16044754/heroku-postgresql-django-comments-tastypie-no-operator-matches-the-given-na

But I don't now how to change that...

**Comment by bashu** [comment]
@gustavklopp did you fixed it?

**Comment by gustavklopp** [comment]
No, but I've used a different solution. that's why I've closed it

**Comment by bashu** [comment]
@gustavklopp what different solution?

**Comment by gustavklopp** [comment]
I've ditched PostgreSQL for another database

**Comment by bashu** [comment]
@gustavklopp what database?

**Comment by gustavklopp** [comment]
MySQL.
