### ISSUE TITLE
New release for Django 1.8/1.9 support?

### ISSUE THREAD

**Issue by vdboor** [django/django-contrib-comments#63]
I noticed there are many changes in git which are not released.
Would you be able to make a release for it, so this app can be used for Django 1.9 too?

Thanks in advance!

**Comment by claudep** [comment]
Many changes? 4 commits. The current 1.6.2 version does support Django 1.9. What makes you think it does not?

**Comment by jaddison** [comment]
I'm running into this exact issue (https://code.djangoproject.com/ticket/24765) with django-contrib-comments.
