### ISSUE TITLE
Custom comment form: AppRegistryNotReady

### ISSUE THREAD

**Issue by girzel** [django/django-contrib-comments#70]
I suspect this will end up being my fault, but I've been scratching my head for days with no result...

I've upgraded to Django 1.9 from 1.7, and to django-contrib-comments from django.contrib.comments, at the same time (my first mistake). Everything's working well, except that I can't get my custom comment form working. Here's the general layout:

my_comments/forms.py:

```python
from django_comments.forms import CommentForm
from django_comments.models import Comment

class MyCommentForm(CommentForm):
# etc.
    def get_comment_model(self):
        return Comment
```

and in my_comments/forms.py:

```python
from my_comments.forms import MyCommentForm

def get_form():
    return MyCommentForm
```

This is giving me an "Apps aren't loaded yet" error. The file my_comments/models.py imports nothing from django_comments but signals. It does import django.contrib.contenttypes, however, which might be relevant to the backtrace:

>   File "mysite/my_comments/__init__.py", line 1, in <module>
>     from my_comments.forms import MyCommentForm
>   File "mysite/my_comments/forms.py", line 1, in <module>
>     from django_comments.forms import CommentForm
>   File "/home/user/dev/pr/src/django-contrib-comments/django_comments/forms.py", line 5, in <module>
>     from django.contrib.contenttypes.models import ContentType
>   File "/home/user/dev/pr/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 159, in <module>
>     class ContentType(models.Model):
>   File "/home/user/dev/pr/lib/python2.7/site-packages/django/db/models/base.py", line 94, in __new__
>     app_config = apps.get_containing_app_config(module)
>   File "/home/user/dev/pr/lib/python2.7/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
>     self.check_apps_ready()
>   File "/home/user/dev/pr/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
>     raise AppRegistryNotReady("Apps aren't loaded yet.")
> django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

But I've removed all the contentypes stuff from my_commets/models.py, and get the same error.

There's no reference to the old django.contrib.comments app anywhere in my code.

I can't think of anything else. But this is obviously supposed to work. What else might I be doing wrong?

Thanks,

**Comment by claudep** [comment]
In Django 1.9, you cannot import anything model-related in the `__init__.py` root file of an application. Even if the model import is indirectly imported by another file. I guess that for you the solution would be stopping to import forms from `mysite/my_comments/__init__.py`.

**Comment by girzel** [comment]
That will leave us unable to use custom comment models and forms, right? Maybe the customization could be switched to a dotted-path entry in settings, like:

```python
COMMENT_MODELS = {
    'model': 'my_comments.models.MyCommet',
    'form': 'my_comments.forms.MyCommentForm'
}
```

Or something like that.

**Comment by tjwudi** [comment]
@girzel Yes. Just import it inside of the `get_model` and `get_form` function. This is not well documented yet.
