### ISSUE TITLE
Customization doesn't work with Django 1.9

### ISSUE THREAD

**Issue by girzel** [django/django-contrib-comments#71]
The advice for customizing django_comments apparently won't work with Django 1.9, as the advised method of putting get_model/get_form functions in the __init__.py file of your comment app will cause a app registry error. I've gotten around this for now like this:

```python
import django_comments
from django_comments.models import Comment
from django_comments.forms import CommentForm

class MyCommentForm(CommentForm):

    def get_comment_model(self):
        return Comment

def my_comments_get_form():
    return MyCommentForm

django_comments.get_form = my_comments_get_form
```
But obviously that's not a great solution. We'll need some other way of customizing the app.

**Comment by claudep** [comment]
Moving imports inside the get_model/get_form functions could solve this. That's what django_comments itself do (see ad2a4ed8dfe6). We probably missed the docs during that commit.

**Comment by girzel** [comment]
I tried it, and it worked just fine! I think an update to the docs is all that's necessary.

Thanks
