### ISSUE TITLE
Progress / Roadmap

### ISSUE THREAD

**Issue by vamsi** [django/django-contrib-comments#77]
I'm just curious about the current state and the maintenance of this project as there are issues to which responses are not made. I wish this django app is maintained well.

**Comment by claudep** [comment]
I'm maintaining this project "by default", in the sense that I'm not using it in my own projects. This minimal maintainership includes fixing critical issue and ensuring compatibility with recent Django versions. I'm trying to review proposed patches, but help is welcome!

**Comment by vamsi** [comment]
It would be nice if you can add a description to the repository.
