### ISSUE TITLE
Allow importing base models only

### ISSUE THREAD

**Issue by julen** [django/django-contrib-comments#83]
We are only using the base models provided by django-contrib-comments, and hence in order to avoid having our project generate tables/models that won't be used, the app is not included under `INSTALLED_APPS`.

However this raises a deprecation warning from Django, which is annoying, potentially masks other important issues and we'd like to get rid of. I believe this could be easily addressed if the abstract base classes are put away in a non-_models.py_ module. In fact, this is what django did ([see ticket 24564](https://code.djangoproject.com/ticket/24564)) with the abstract models from `django.contrib.auth`.

@claudep would you be up to accepting a patch for this and making a release with it? TIA.

**Comment by claudep** [comment]
Absolutely, I support having abstract models outside of models.py.

**Comment by julen** [comment]
Wonderful! I will only be able to get to it on Tuesday, although if you are
up to it before then please go ahead.

**Comment by claudep** [comment]
@julen Please review!

**Comment by claudep** [comment]
Julen, I'll wait for your input before preparing a release.

**Comment by julen** [comment]
All is fine in my testing, @claudep. It would be sweet if you could make a new release which includes this change. Thanks again!

**Comment by claudep** [comment]
Done, 1.7.1 is out!
