### ISSUE TITLE
RuntimeError: Model class django_comments.models.Comment doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

### ISSUE THREAD

**Issue by yeago** [django/django-contrib-comments#87]
Seems like as of 1.9 you can't _really_ extend this app because any attempt to do so triggers this RunTimeError. The documentation doesn't mention keeping django_comments in INSTALLED_APPS in the event of customization.

**Comment by claudep** [comment]
This should be fixed now with the recent 1.7.1 release and if you extend `django_comments.abstracts.CommentAbstractModel`. Could you test that?

**Comment by yeago** [comment]
Ah okay, but now

from django_comments.admin import CommentsAdmin

triggers the same thing

**Comment by julen** [comment]
If I'm not mistaken this was already fixed (the PR merged at least) and can be closed.

**Comment by claudep** [comment]
Sure, #88 was merged.
