### ISSUE TITLE
Admin class is sometimes not registered (1.7.2 regression)

### ISSUE THREAD

**Issue by czpython** [django/django-contrib-comments#95]
Hello,

The following commit https://github.com/django/django-contrib-comments/commit/e51cbd9700900d25180a9f42e649cb4274d882ce introduced a regression in regards to the admin.

[This](https://github.com/django/django-contrib-comments/commit/e51cbd9700900d25180a9f42e649cb4274d882ce#diff-293b17c4b19baa0c9755210bfe467469R93) line:

```python
Klass._meta.app_label is "django_comments"
```

assumes that both strings share the same memory id, which is true in certain cases (usually inside a REPL):

```
>>> id("django_comments")
4315523368
>>> id("django_comments")
4315523368
>>> id("django_comments")
4315523368
```

But when executing this in a script, the ids are different.

So currently `Klass._meta.app_label is "django_comments"` returns `False` even though both strings are `'django_comments'`.

**Comment by jaddison** [comment]
@claudep, can we get a new release with this fix? I have a feeling it's behind a few issues out in the wild (I know it's causing issues in my project).

**Comment by claudep** [comment]
Sure, it's definitely on my TODO for this week.

**Comment by claudep** [comment]
1.7.3 is out, https://pypi.python.org/pypi/django-contrib-comments

**Comment by jaddison** [comment]
Awesome, thanks!
